EdPlatform rework + project clean
VikMoskalenko/ThirdTeam_Study pull request #16
Opened 2024-06-10 17:38 UTC by DanyloNaumenko

To many changes, no comments.

2024-06-11 07:21 UTC, Vadim211 requested changes

2024-06-11 07:21 UTC, Vadim211 commented on Managers/EdPlatformManager.cs
> +        public void GetSupportInfo()
This can be record type as it was required in prev home work

2024-06-11 07:21 UTC, Vadim211 commented on Program.cs
>              studentList.AddStudent(1234575, "2016", "Francisco", "Ramírez");
I suppose comments can be deleted

2024-06-11 07:52 UTC, IlliaKrasheninnikov commented on Extentions/LessonExtension.cs
>                  if (student.Id == id)
Student ID was changed to Guid id

2024-06-11 08:15 UTC, IlliaKrasheninnikov commented on Managers/OutputManager.cs
Can you please add Input manager. Just copy from Program.cs UserInput function.

2024-06-11 17:00 UTC, VikMoskalenko approved these changes

2024-06-13 18:54 UTC, DanyloNaumenko commented on Managers/OutputManager.cs
Done

2024-06-13 19:01 UTC, merged