Ikr 4
VikMoskalenko/ThirdTeam_Study pull request #19
Opened 2024-06-17 19:39 UTC by IlliaKrasheninnikov

Main updated. The project works (I hope so)

2024-06-17 19:42 UTC, Vadim211 approved these changes
LGTM

2024-06-17 19:58 UTC, DanyloNaumenko commented on Program.cs
> +                Teacher = tutor_manager.CreateTutor("Вікторія", "Вакарчук", new DateOnly(2002, 08, 08)),
Could you please create Teacher through the edPlatformManager.SignUp() method

2024-06-17 20:00 UTC, DanyloNaumenko requested changes
Good

2024-06-18 09:42 UTC, DanyloNaumenko approved these changes
LGTM

2024-06-18 10:02 UTC, merged